version: '2'
volumes:
  node_modules:

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile.lndrelay
    volumes:
      - .:/relay
      - .lnd/:/relay/.lnd
      - node_modules:/relay/node_modules
    ports:
      - "3000:3000"
    command: "lnd --accept-keysend --configfile=/relay/.lnd/lnd.conf && npm start"
    environment:
      - PORT=3000
      - NODE_IP=mynodeip
      - NODE_ALIAS=myalias
      - NODE_ENV=production
      - LND_IP=host.docker.internal
      - LND_PORT=11009
      - MACAROON_LOCATION=xxxx
      - TLS_LOCATION=xxx
      - LND_LOG_LOCATION=xxxx